import type { Project } from "./types"

export const projects: Project[] = [
  {
    slug: "wetbulb35",
    title: "WetBulb35",
    description: "Climate safety app providing real-time heat risk assessments and alerts.",
    technologies: ["Next.js", "TypeScript", "Weather API", "D3.js"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    githubUrl: "https://github.com/yourusername/wetbulb35",
    liveUrl: "https://wetbulb35.com",
    featured: true,
    content: "# WetBulb35\n\nDetailed content about the project...",
    date: "2023-10-15",
    type: "software",
  },
  {
    slug: "e-commerce-platform",
    title: "E-Commerce Platform",
    description: "A modern e-commerce solution with advanced product filtering and search capabilities.",
    technologies: ["Vue.js", "Nuxt", "Stripe", "Tailwind CSS"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    githubUrl: "https://github.com/yourusername/ecommerce",
    liveUrl: "https://demo-ecommerce.example.com",
    featured: true,
    content: "# E-Commerce Platform\n\nDetailed content about the project...",
    date: "2023-08-20",
    type: "software",
  },
  {
    slug: "data-visualization-dashboard",
    title: "Data Visualization Dashboard",
    description: "Interactive dashboard for visualizing complex datasets with customizable charts.",
    technologies: ["React", "D3.js", "TypeScript", "Material UI"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    githubUrl: "https://github.com/yourusername/data-viz",
    liveUrl: "https://data-viz.example.com",
    featured: false,
    content: "# Data Visualization Dashboard\n\nDetailed content about the project...",
    date: "2023-06-10",
    type: "software",
  },
  {
    slug: "task-management-app",
    title: "Task Management App",
    description: "A productivity tool for teams to manage tasks, deadlines, and collaboration.",
    technologies: ["React", "Firebase", "Tailwind CSS", "React DnD"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    githubUrl: "https://github.com/yourusername/task-app",
    liveUrl: "https://tasks.example.com",
    featured: false,
    content: "# Task Management App\n\nDetailed content about the project...",
    date: "2023-04-05",
    type: "software",
  },
  {
    slug: "eco-friendly-product",
    title: "Eco-Friendly Product",
    description: "Sustainable solution for everyday use that reduces plastic waste and environmental impact.",
    technologies: ["Product Design", "Sustainability", "3D Printing", "Recycled Materials"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    githubUrl: "",
    liveUrl: "https://eco-product.example.com",
    featured: true,
    content: "# Eco-Friendly Product\n\nDetailed content about the project...",
    date: "2023-05-12",
    type: "physical",
  },
  {
    slug: "smart-home-device",
    title: "Smart Home Device",
    description: "IoT device that helps homeowners monitor and reduce their energy consumption.",
    technologies: ["IoT", "Hardware Design", "Mobile App", "Energy Efficiency"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    githubUrl: "https://github.com/yourusername/smart-home",
    liveUrl: "",
    featured: false,
    content: "# Smart Home Device\n\nDetailed content about the project...",
    date: "2022-11-30",
    type: "physical",
  },
]

